---
- hosts: localhost
  pre_tasks:
  - name: Update local apt cache
    become: true
    apt:
      update_cache: true
      cache_valid_time: 3600
  vars:
    user_id: "{{ ansible_user_id }}"
  tasks:
  - name: Ensure .ssh directory exists
    file:
      dest: ~/.ssh
      mode: '0700'
      state: directory

  - name: Install public SSH key
    copy:
      src: "{{ playbook_dir }}/ssh/id_ed25519.pub"
      dest: ~/.ssh/id_ed25519.pub
      mode: '0644'

  - name: Install private SSH key
    copy:
      src: "{{ playbook_dir }}/ssh/id_ed25519"
      dest: ~/.ssh/id_ed25519
      mode: '0600'

  - name: Set authorized key taken from file
    authorized_key:
      user: "{{ user_id }}"
      key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_ed25519.pub') }}"

  - name: Install system packages
    become: true
    apt:
      name:
      - i3
      - autorandr
      - zsh

  - name: Change user's shell to zsh
    become: true
    user:
      name: "{{ user_id }}"
      shell: /bin/zsh

  - name: Check for existing Nix installation
    command: nix --version
    failed_when: false
    changed_when: false
    register: nix_version_output

  - name: Install Nix
    become: true
    shell: |
      sh <(curl -L https://nixos.org/nix/install) </dev/null --daemon
    args:
      executable: /bin/bash
    when: nix_version_output.rc == 2

  - name: Clone Home Manager configuration
    git:
      repo: git@github.com:eotsn/home-manager.git
      dest: ~/.config/home-manager
      accept_hostkey: true
      version: main

  - name: Check for existing Home Manager installation
    command: home-manager --version
    failed_when: false
    changed_when: false
    register: home_manager_version_output

  - name: Install Home Manager
    shell: |
      nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
      nix-channel --update
      nix-shell '<home-manager>' -A install
    args:
      executable: /bin/bash
    when: home_manager_version_output.rc == 2

  - name: Clone Neovim configuration
    git:
      repo: git@github.com:eotsn/kickstart.nvim.git
      dest: ~/.config/nvim
      accept_hostkey: true
      version: master
